from typing import List, Literal, Optional

from fastapi import FastAPI
from pydantic import BaseModel, ConfigDict, Field, HttpUrl

app = FastAPI(title="SkinAIBot Mock AI Service", version="0.1.0")


class AnalyzeRequest(BaseModel):
    model_config = ConfigDict(protected_namespaces=())

    analysis_id: str
    image_url: HttpUrl
    model_version: Optional[str] = "v1"


class Prediction(BaseModel):
    label: str
    confidence: float = Field(ge=0, le=1)


class AnalyzeResponse(BaseModel):
    model_config = ConfigDict(protected_namespaces=())

    analysis_id: str
    status: Literal["completed", "failed", "processing"]
    model_version: str
    predictions: List[Prediction]
    confidence_status: Literal["high", "moderate", "low"]
    explanation: str
    recommendation: str
    disclaimer: str


class ChatRequest(BaseModel):
    session_id: str
    message: str
    analysis_id: Optional[str] = None


class ChatResponse(BaseModel):
    response: str
    disclaimer: str


@app.post("/ai/analyze", response_model=AnalyzeResponse)
def analyze_image(req: AnalyzeRequest):
    return AnalyzeResponse(
        analysis_id=req.analysis_id,
        status="completed",
        model_version="mock-efficientnet-v1",
        predictions=[
            Prediction(label="mock_class_a", confidence=0.60),
            Prediction(label="mock_class_b", confidence=0.25),
            Prediction(label="mock_class_c", confidence=0.15),
        ],
        confidence_status="low",
        explanation=(
            "This is a placeholder explanation generated by the MOCK AI service. "
            "It is NOT based on the uploaded image."
        ),
        recommendation=(
            "MOCK recommendation: no medical action is suggested. "
            "Consult a qualified dermatologist for any real skin concerns."
        ),
        disclaimer=(
            "SYNTHETIC MOCK DATA for development and testing only. "
            "This is NOT a medical diagnosis and is NOT based on the uploaded image."
        ),
    )


@app.post("/ai/chat", response_model=ChatResponse)
def chat_ai(req: ChatRequest):
    return ChatResponse(
        response=f"[MOCK] Simulated chat reply to '{req.message}'. This is not medical advice.",
        disclaimer="SYNTHETIC MOCK DATA for development and testing only. NOT medical advice.",
    )


@app.get("/ai/health")
def health():
    return {"status": "healthy", "service": "Mock AI"}
